apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: admin-panel
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - admin.kigawa.net
      secretName: admin-panel-tls
