apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: kigawa-net-admin-panel

images:
  - name: harbor.kigawa.net/library/admin-panel
    newTag: main-f5c85cf24d8df0a11084ed128e78ac9450e9047c
  - name: harbor.kigawa.net/library/admin-panel-api
    newTag: main-f5c85cf24d8df0a11084ed128e78ac9450e9047c

patches:
  - path: replica-patch.yaml
  - path: api-replica-patch.yaml
  - path: ingress-tls-patch.yaml
