apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: kigawa-net-admin-panel

images:
  - name: harbor.kigawa.net/library/admin-panel
    newTag: main-a012a865c4a8bae6354aa949b6a5b1af9a5b80f5

patches:
  - path: replica-patch.yaml
  - path: ingress-tls-patch.yaml
