apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: kigawa-net-admin-panel

images:
  - name: harbor.kigawa.net/library/admin-panel
    newTag: main-d25b385b8044d35e2cbaa709da78355d4e2878a5

patches:
  - path: replica-patch.yaml
  - path: ingress-tls-patch.yaml
