apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: admin-panel-github-app-bws
spec:
  organizationId: "a2b57f3d-6e2b-4467-b499-b31e00bfd804"
  secretName: admin-panel-github-app
  authToken:
    secretName: bitwarden-sec
    secretKey: token
  map:
    - bwSecretId: "97b6eba7-6bd2-418d-9d64-b48a007a097a" # kigawa-net-private-key
      secretKeyName: private-key
    - bwSecretId: "8a261bc3-cbfb-4e27-958e-b48d00ac0887" # admin-panel-github-app-ci-token (kigawa-net/infra platform/admin-panel)
      secretKeyName: ci-token
