apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: admin-panel-mariadb-bws
spec:
  organizationId: "a2b57f3d-6e2b-4467-b499-b31e00bfd804"
  secretName: admin-panel-mariadb
  authToken:
    secretName: bitwarden-sec
    secretKey: token
  map:
    # terraform output(platform/admin-panel)の実値(kigawa-net/infra#137)。
    - bwSecretId: "74a6fe9c-c0f0-4399-a251-b4cd011a0037"
      secretKeyName: root-password
    - bwSecretId: "e6242528-1c26-40bd-a816-b4cd011a0035"
      secretKeyName: app-password
